### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by Bra1nsen** [Tronde/raspberrypi-dd-backup#1]
thanks for sharing your work Jörg

iam an absolut beginner with linux/raspberry, but i know how important backups are.

could you give a step by step explanation? I would like to backup my image to /home/pi/mnt/gdrive

**Comment by Bra1nsen** [comment]
How do I know my backup source?

**Comment by Bra1nsen** [comment]
And what do you mean with "Copy CONFIG.sample to config" ?

**Comment by Tronde** [comment]
Hi @Bra1nsen, I added some additional info to the README.md. Please check if that answers your question.

Regards,  
Jörg
